ALTER TABLE cs_questions
    ADD COLUMN IF NOT EXISTS content_mode VARCHAR(20) NOT NULL DEFAULT 'LEGACY_TEXT',
    ADD COLUMN IF NOT EXISTS content_blocks TEXT,
    ADD COLUMN IF NOT EXISTS grading_mode VARCHAR(30) NOT NULL DEFAULT 'DEFAULT_BY_TYPE',
    ADD COLUMN IF NOT EXISTS metadata TEXT;
