CREATE TABLE IF NOT EXISTS cs_question_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stage_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    claim_type VARCHAR(40) NOT NULL,
    description TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    selected_choice_no SMALLINT,
    submitted_answer TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_cs_question_claims_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_question_claims_stage
        FOREIGN KEY (stage_id) REFERENCES cs_stages (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_question_claims_question
        FOREIGN KEY (question_id) REFERENCES cs_questions (id) ON DELETE CASCADE,
    CONSTRAINT chk_cs_question_claims_type
        CHECK (claim_type IN ('INCORRECT_ANSWER', 'INCORRECT_EXPLANATION', 'QUESTION_TEXT_ERROR', 'OTHER')),
    CONSTRAINT chk_cs_question_claims_status
        CHECK (status IN ('RECEIVED', 'REVIEWED', 'RESOLVED'))
);

CREATE INDEX IF NOT EXISTS idx_cs_question_claims_stage_created_at
    ON cs_question_claims (stage_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cs_question_claims_user_created_at
    ON cs_question_claims (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cs_question_claims_user_question_created_at
    ON cs_question_claims (user_id, question_id, created_at DESC);
