CREATE TABLE IF NOT EXISTS cs_stage_solve_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stage_id BIGINT NOT NULL,
    max_solve INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_cs_stage_solve_records_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_stage_solve_records_stage
        FOREIGN KEY (stage_id) REFERENCES cs_stages (id) ON DELETE CASCADE,
    CONSTRAINT uk_cs_stage_solve_records_user_stage
        UNIQUE (user_id, stage_id),
    CONSTRAINT chk_cs_stage_solve_records_max_solve
        CHECK (max_solve >= 0)
);

CREATE INDEX IF NOT EXISTS idx_cs_stage_solve_records_user_id
    ON cs_stage_solve_records (user_id);

CREATE INDEX IF NOT EXISTS idx_cs_stage_solve_records_stage_id
    ON cs_stage_solve_records (stage_id);
