-- PostgreSQL baseline schema for Peekle
-- This migration creates the latest schema shape directly.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_id VARCHAR(255) NOT NULL UNIQUE,
    provider VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) UNIQUE,
    profile_img VARCHAR(255) NOT NULL,
    profile_img_thumb VARCHAR(255) NOT NULL,
    profile_img_type VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
    boj_id VARCHAR(255),
    extension_token VARCHAR(100) UNIQUE,
    extension_token_updated_at TIMESTAMP(6),
    league VARCHAR(20) DEFAULT 'STONE',
    league_point INT DEFAULT 0,
    league_group_id BIGINT,
    streak_current INT DEFAULT 0,
    streak_max INT DEFAULT 0,
    max_league VARCHAR(20) NOT NULL DEFAULT 'STONE',
    is_deleted BOOLEAN DEFAULT FALSE,
    last_solved_date DATE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    tier VARCHAR(255) NOT NULL,
    url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_key VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS problem_tags (
    problem_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (problem_id, tag_id),
    CONSTRAINT fk_problem_tags_problem FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE CASCADE,
    CONSTRAINT fk_problem_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS league_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier VARCHAR(20) NOT NULL,
    season_week INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS league_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    league VARCHAR(20) NOT NULL,
    final_point INT NOT NULL,
    result VARCHAR(20) NOT NULL,
    season_week INT NOT NULL,
    closed_at TIMESTAMP(6) NOT NULL,
    rank_value INT,
    league_group_id BIGINT,
    is_viewed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_league_history_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS study_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ranking_point INT DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_study_room_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS study_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_study_member_room FOREIGN KEY (study_room_id) REFERENCES study_rooms (id),
    CONSTRAINT fk_study_member_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS study_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_room_id BIGINT NOT NULL,
    problem_id BIGINT NULL,
    custom_title VARCHAR(255),
    custom_link VARCHAR(255),
    problem_type VARCHAR(20) NOT NULL DEFAULT 'BOJ',
    problem_date DATE NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_study_problem_room FOREIGN KEY (study_room_id) REFERENCES study_rooms (id),
    CONSTRAINT fk_study_problem_user FOREIGN KEY (created_by) REFERENCES users (id)
);

ALTER TABLE study_members
    ADD COLUMN IF NOT EXISTS last_study_problem_id BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_study_member_last_problem'
    ) THEN
        ALTER TABLE study_members
            ADD CONSTRAINT fk_study_member_last_problem
            FOREIGN KEY (last_study_problem_id) REFERENCES study_problems (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS study_chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    parent_id BIGINT,
    metadata TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_chat_log_room FOREIGN KEY (study_room_id) REFERENCES study_rooms (id),
    CONSTRAINT fk_chat_log_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_chat_log_parent FOREIGN KEY (parent_id) REFERENCES study_chat_logs (id)
);

CREATE TABLE IF NOT EXISTS submission_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    source_type VARCHAR(255),
    room_id BIGINT,
    study_problem_id BIGINT,
    problem_title VARCHAR(255),
    external_id VARCHAR(255),
    problem_tier VARCHAR(255),
    tag VARCHAR(255),
    code TEXT,
    memory INT,
    execution_time INT,
    language VARCHAR(255),
    result VARCHAR(50),
    is_success BOOLEAN,
    submitted_at TIMESTAMP(6),
    CONSTRAINT fk_submission_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_submission_problem FOREIGN KEY (problem_id) REFERENCES problems (id),
    CONSTRAINT fk_submission_study_problem FOREIGN KEY (study_problem_id) REFERENCES study_problems (id)
);

CREATE TABLE IF NOT EXISTS testcases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_room_id BIGINT NOT NULL,
    study_problem_id BIGINT NOT NULL,
    input TEXT,
    expected_output TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_testcases_room FOREIGN KEY (study_room_id) REFERENCES study_rooms (id) ON DELETE CASCADE,
    CONSTRAINT fk_testcases_study_problem FOREIGN KEY (study_problem_id) REFERENCES study_problems (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS study_problem_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_member_id BIGINT NOT NULL,
    study_problem_id BIGINT NOT NULL,
    code TEXT,
    language VARCHAR(50),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_study_problem_draft_member
        FOREIGN KEY (study_member_id) REFERENCES study_members (id) ON DELETE CASCADE,
    CONSTRAINT fk_study_problem_draft_problem
        FOREIGN KEY (study_problem_id) REFERENCES study_problems (id) ON DELETE CASCADE,
    CONSTRAINT uk_study_problem_draft_member_problem
        UNIQUE (study_member_id, study_problem_id)
);

CREATE TABLE IF NOT EXISTS submission_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    line_start INT NOT NULL,
    line_end INT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    comment_type VARCHAR(20) NOT NULL DEFAULT 'INLINE',
    CONSTRAINT fk_submission_comments_submission
        FOREIGN KEY (submission_id) REFERENCES submission_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_comments_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_submission_comments_parent
        FOREIGN KEY (parent_id) REFERENCES submission_comments (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS point_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    amount INT NOT NULL,
    description VARCHAR(255),
    metadata TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_point_log_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS workbooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    creator_id BIGINT NOT NULL,
    bookmark_count INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_workbook_creator FOREIGN KEY (creator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS workbook_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workbook_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    order_index INT NOT NULL,
    CONSTRAINT fk_workbook_problem_workbook
        FOREIGN KEY (workbook_id) REFERENCES workbooks (id) ON DELETE CASCADE,
    CONSTRAINT fk_workbook_problem_problem
        FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS workbook_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workbook_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_workbook_bookmark_workbook_user UNIQUE (workbook_id, user_id),
    CONSTRAINT fk_workbook_bookmark_workbook
        FOREIGN KEY (workbook_id) REFERENCES workbooks (id) ON DELETE CASCADE,
    CONSTRAINT fk_workbook_bookmark_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_league ON users (league);
CREATE INDEX IF NOT EXISTS idx_users_league_group ON users (league_group_id);
CREATE INDEX IF NOT EXISTS idx_submission_user ON submission_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_submission_problem ON submission_logs (problem_id);
CREATE INDEX IF NOT EXISTS idx_submission_study_problem ON submission_logs (study_problem_id);
CREATE INDEX IF NOT EXISTS idx_point_log_user ON point_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_league_history_user ON league_history (user_id);
CREATE INDEX IF NOT EXISTS idx_league_history_season ON league_history (season_week);
CREATE INDEX IF NOT EXISTS idx_league_groups_season ON league_groups (season_week);
CREATE INDEX IF NOT EXISTS idx_study_member_room ON study_members (study_room_id);
CREATE INDEX IF NOT EXISTS idx_study_member_user ON study_members (user_id);
CREATE INDEX IF NOT EXISTS idx_study_member_last_problem ON study_members (last_study_problem_id);
CREATE INDEX IF NOT EXISTS idx_study_problem_room ON study_problems (study_room_id);
CREATE INDEX IF NOT EXISTS idx_chat_log_room ON study_chat_logs (study_room_id);
CREATE INDEX IF NOT EXISTS idx_problem_tags_tag_id ON problem_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_testcases_room_problem ON testcases (study_room_id, study_problem_id);
CREATE INDEX IF NOT EXISTS idx_study_problem_draft_member ON study_problem_drafts (study_member_id);
CREATE INDEX IF NOT EXISTS idx_study_problem_draft_problem ON study_problem_drafts (study_problem_id);
CREATE INDEX IF NOT EXISTS idx_submission_comments_submission_created ON submission_comments (submission_id, created_at);
CREATE INDEX IF NOT EXISTS idx_submission_comments_parent ON submission_comments (parent_id);
CREATE INDEX IF NOT EXISTS idx_submission_comments_type ON submission_comments (comment_type);
CREATE INDEX IF NOT EXISTS idx_submission_comments_deleted ON submission_comments (is_deleted);
CREATE INDEX IF NOT EXISTS idx_workbooks_creator ON workbooks (creator_id);
CREATE INDEX IF NOT EXISTS idx_workbook_problems_workbook ON workbook_problems (workbook_id);
CREATE INDEX IF NOT EXISTS idx_workbook_bookmarks_user ON workbook_bookmarks (user_id);
