ALTER TABLE submission_logs
    ADD COLUMN IF NOT EXISTS submit_id VARCHAR(255);

CREATE UNIQUE INDEX IF NOT EXISTS uk_submission_logs_user_problem_submit_id
    ON submission_logs (user_id, problem_id, submit_id)
    WHERE submit_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS tag_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id BIGINT NOT NULL,
    source VARCHAR(50) NOT NULL,
    external_key VARCHAR(255) NOT NULL,
    external_name VARCHAR(255),
    CONSTRAINT fk_tag_mappings_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT uk_tag_mappings_source_external_key
        UNIQUE (source, external_key)
);

CREATE INDEX IF NOT EXISTS idx_tag_mappings_tag_id
    ON tag_mappings (tag_id);
