ALTER TABLE problems
    ADD COLUMN IF NOT EXISTS leetcode_rating DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS difficulty_source VARCHAR(50);

UPDATE problems
SET difficulty_source = 'SOLVED_AC'
WHERE source = 'BOJ'
    AND difficulty_source IS NULL;

CREATE TABLE IF NOT EXISTS leetcode_problem_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_number INTEGER,
    title VARCHAR(255) NOT NULL,
    title_slug VARCHAR(255) NOT NULL,
    title_zh VARCHAR(255),
    rating DOUBLE PRECISION NOT NULL,
    contest_slug VARCHAR(255),
    problem_index VARCHAR(20),
    contest_id_en VARCHAR(255),
    contest_id_zh VARCHAR(255),
    CONSTRAINT uk_leetcode_problem_ratings_title_slug UNIQUE (title_slug)
);

CREATE INDEX IF NOT EXISTS idx_leetcode_problem_ratings_problem_number
    ON leetcode_problem_ratings (problem_number);
