ALTER TABLE users
    ADD COLUMN IF NOT EXISTS rec_level_x10 INT NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS last_recommended_date DATE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_rec_level_x10'
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT chk_users_rec_level_x10
            CHECK (rec_level_x10 BETWEEN 10 AND 300);
    END IF;
END $$;

ALTER TABLE problems
    ADD COLUMN IF NOT EXISTS accepted_user_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS level INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS language VARCHAR(5) NOT NULL DEFAULT 'ko';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_problems_accepted_user_count'
    ) THEN
        ALTER TABLE problems
            ADD CONSTRAINT chk_problems_accepted_user_count
            CHECK (accepted_user_count >= 0);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_problems_level'
    ) THEN
        ALTER TABLE problems
            ADD CONSTRAINT chk_problems_level
            CHECK (level BETWEEN 0 AND 30);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_problems_language'
    ) THEN
        ALTER TABLE problems
            ADD CONSTRAINT chk_problems_language
            CHECK (language IN ('ko', 'en', 'ja'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS recommend_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    reason TEXT,
    order_index INT NOT NULL,
    solved BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_recommend_problems_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_recommend_problems_problem
        FOREIGN KEY (problem_id) REFERENCES problems (id),
    CONSTRAINT uk_recommend_problems_user_order
        UNIQUE (user_id, order_index)
);

CREATE INDEX IF NOT EXISTS idx_recommend_problems_user_order
    ON recommend_problems (user_id, order_index);

CREATE INDEX IF NOT EXISTS idx_recommend_problems_user_solved
    ON recommend_problems (user_id, solved);

CREATE TABLE IF NOT EXISTS recommend_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    feedback VARCHAR(20) NOT NULL,
    CONSTRAINT fk_recommend_feedbacks_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_recommend_feedbacks_feedback'
    ) THEN
        ALTER TABLE recommend_feedbacks
            ADD CONSTRAINT chk_recommend_feedbacks_feedback
            CHECK (feedback IN ('TOO_EASY', 'JUST_RIGHT', 'TOO_HARD'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_recommend_feedbacks_user
    ON recommend_feedbacks (user_id);
