CREATE TABLE IF NOT EXISTS cs_domains (
    id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS cs_domain_tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id INT NOT NULL,
    track_no SMALLINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    CONSTRAINT fk_cs_domain_tracks_domain
        FOREIGN KEY (domain_id) REFERENCES cs_domains (id) ON DELETE CASCADE,
    CONSTRAINT uk_cs_domain_tracks_domain_track_no
        UNIQUE (domain_id, track_no)
);

CREATE TABLE IF NOT EXISTS cs_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id BIGINT NOT NULL,
    stage_no SMALLINT NOT NULL,
    CONSTRAINT fk_cs_stages_track
        FOREIGN KEY (track_id) REFERENCES cs_domain_tracks (id) ON DELETE CASCADE,
    CONSTRAINT uk_cs_stages_track_stage_no
        UNIQUE (track_id, stage_no)
);

CREATE TABLE IF NOT EXISTS cs_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id BIGINT NOT NULL,
    question_type VARCHAR(30) NOT NULL,
    prompt TEXT NOT NULL,
    explanation TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_cs_questions_stage
        FOREIGN KEY (stage_id) REFERENCES cs_stages (id) ON DELETE CASCADE,
    CONSTRAINT chk_cs_questions_type
        CHECK (question_type IN ('MULTIPLE_CHOICE', 'SHORT_ANSWER', 'OX'))
);

CREATE TABLE IF NOT EXISTS cs_question_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    choice_no SMALLINT NOT NULL,
    content TEXT NOT NULL,
    is_answer BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_cs_question_choices_question
        FOREIGN KEY (question_id) REFERENCES cs_questions (id) ON DELETE CASCADE,
    CONSTRAINT uk_cs_question_choices_question_choice_no
        UNIQUE (question_id, choice_no)
);

CREATE TABLE IF NOT EXISTS cs_question_short_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    answer_text VARCHAR(200) NOT NULL,
    normalized_answer VARCHAR(200) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_cs_question_short_answers_question
        FOREIGN KEY (question_id) REFERENCES cs_questions (id) ON DELETE CASCADE,
    CONSTRAINT uk_cs_question_short_answers_question_normalized
        UNIQUE (question_id, normalized_answer)
);

CREATE TABLE IF NOT EXISTS cs_user_profiles (
    user_id BIGINT PRIMARY KEY,
    current_domain_id INT NULL,
    CONSTRAINT fk_cs_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_user_profiles_current_domain
        FOREIGN KEY (current_domain_id) REFERENCES cs_domains (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS cs_user_domain_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    domain_id INT NOT NULL,
    current_track_no SMALLINT NOT NULL DEFAULT 1,
    current_stage_no SMALLINT NOT NULL DEFAULT 1,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_cs_user_domain_progress_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_user_domain_progress_domain
        FOREIGN KEY (domain_id) REFERENCES cs_domains (id) ON DELETE CASCADE,
    CONSTRAINT uk_cs_user_domain_progress_user_domain
        UNIQUE (user_id, domain_id)
);

CREATE TABLE IF NOT EXISTS cs_wrong_problems (
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    domain_id INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    review_correct_count INT NOT NULL DEFAULT 0,
    wrong_count INT NOT NULL DEFAULT 1,
    last_wrong_at TIMESTAMP(6) NOT NULL,
    cleared_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (user_id, question_id),
    CONSTRAINT fk_cs_wrong_problems_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_wrong_problems_question
        FOREIGN KEY (question_id) REFERENCES cs_questions (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_wrong_problems_domain
        FOREIGN KEY (domain_id) REFERENCES cs_domains (id) ON DELETE CASCADE,
    CONSTRAINT chk_cs_wrong_problems_status
        CHECK (status IN ('ACTIVE', 'CLEARED')),
    CONSTRAINT chk_cs_wrong_problems_counts
        CHECK (review_correct_count >= 0 AND wrong_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_cs_domain_tracks_domain_id
    ON cs_domain_tracks (domain_id);
CREATE INDEX IF NOT EXISTS idx_cs_stages_track_id
    ON cs_stages (track_id);
CREATE INDEX IF NOT EXISTS idx_cs_questions_stage_id
    ON cs_questions (stage_id);
CREATE INDEX IF NOT EXISTS idx_cs_question_choices_question_id
    ON cs_question_choices (question_id);
CREATE INDEX IF NOT EXISTS idx_cs_question_short_answers_question_id
    ON cs_question_short_answers (question_id);
CREATE INDEX IF NOT EXISTS idx_cs_user_domain_progress_user_id
    ON cs_user_domain_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_cs_wrong_problems_question_id
    ON cs_wrong_problems (question_id);
CREATE INDEX IF NOT EXISTS idx_cs_wrong_problems_status
    ON cs_wrong_problems (status);
CREATE INDEX IF NOT EXISTS idx_cs_wrong_problems_user_domain_status_updated_at
    ON cs_wrong_problems (user_id, domain_id, status, updated_at DESC);
