CREATE TABLE IF NOT EXISTS cs_stage_attempt_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    domain_id INT NOT NULL,
    track_no SMALLINT NOT NULL,
    stage_no SMALLINT NOT NULL,
    correct_count INT NOT NULL,
    total_count INT NOT NULL,
    is_review BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_cs_stage_attempt_logs_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_stage_attempt_logs_domain
        FOREIGN KEY (domain_id) REFERENCES cs_domains (id) ON DELETE CASCADE,
    CONSTRAINT chk_cs_stage_attempt_logs_counts
        CHECK (correct_count >= 0 AND total_count > 0 AND correct_count <= total_count)
);

CREATE INDEX IF NOT EXISTS idx_cs_stage_attempt_logs_user_completed_at
    ON cs_stage_attempt_logs (user_id, completed_at DESC);

CREATE INDEX IF NOT EXISTS idx_cs_stage_attempt_logs_user_review_completed_at
    ON cs_stage_attempt_logs (user_id, is_review, completed_at DESC);
